name: 'ArgoCD CLI Sync'
description: 'Syncs the ARGO Application'
branding:
  color: 'green'
  icon: 'upload-cloud'
inputs:
  argo-token:
    description: 'API Token with Sync permission to ArgoCD'
    required: false
    default: ''
  argo-url:
    description: 'argocd server endpoint'
    required: false
    default: ''
  argo-application:
    description: 'argo application name'
    required: false
    default: ''
  argo-command:
    description: 'argo command to use with argocd'
    required: false
    default: 'app'
  argo-sub-command:
    description: 'argo sub command to use with argocd'
    required: false
    default: 'sync'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    ARGO_TOKEN: ${{ inputs.argo-token }}
    ARGO_URL: ${{ inputs.argo-url }}
    ARGO_APPLICATION: ${{ inputs.argo-application }}
    ARGOCD_COMMAND: ${{ inputs.argo-command }}
    ARGOCD_SUB_COMMAND: ${{ inputs.argo-sub-command }}
